apiVersion: todo.ibm.com/v1alpha1
kind: Todo
metadata:
  name: example-todo
  replicaCount: 3
  namespace: "kubeapp"
  mongodb: 
    host: "mongodb.kubeapp"
    username: "YWRtaW4="
    password: "YWRtaW4="
    secret: "aGVsbG8="
    endpoint: "reporting"
  buildconfig:
    uri: "https://github.com/SaifRehman/openshift-microservice.git"
  cm:
    data: '{"Username":{"type":String},"Task":{"type":String},"Completed":{"type":Boolean},"Time":{"type":String}}'