apiVersion: mongorest.ibm.com/v1alpha1
kind: Mongorest
metadata:
  name: todomicroservice
spec:
  replicaCount: 3
  namespace: "kubeapp"
  metadata:
    name: todo-microservice
  mongodb: 
    host: "mongodb.kubeapp"
    username: "YWRtaW4="
    password: "YWRtaW4="
    endpoint: "license"
    db: "sampledb"
    schema: "Todo"
    model: "{'task':'String','completed':'Boolean','uid':'String'}"
  buildconfig: 
    imagename: "todo-microservice:latest"
  routes:
    host: "todo-microservice-kubeapp.apps.192.168.64.20.nip.io"