apiVersion: mongorest.ibm.com/v1alpha1
kind: Mongorest
metadata:
  name: reservationmicroservice
spec:
  replicaCount: 3
  namespace: "kubeapp"
  metadata:
    name: reservation-microservice
  mongodb: 
    host: "mongodb.kubeapp"
    username: "YWRtaW4="
    password: "YWRtaW4="
    endpoint: "reservation"
    db: "sampledb"
    schema: "Reservation"
    model: "{'firstname':'String','lastname':'String','uid':'String'}"
  buildconfig: 
    imagename: "reservation-microservice:latest"
  routes:
    host: "reservation-microservice-kubeapp.apps.192.168.64.21.nip.io"