apiVersion: v1
kind: Secret
metadata:
  name: "mongo-rest"
  labels:
    app: "{{ .Values.metadata.name }}"
  namespace: "{{ .Values.namespace }}"
type: Opaque
data:
  SECRET: "{{ .Values.mongodb.secret }}"
  MONGOUSERNAME: "{{ .Values.mongodb.username }}"
  MONGOPASSWORD: "{{ .Values.mongodb.password }}"