replicaCount: 2

metadata:
 name: listingsvc 
 label: listingsvc
readinessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10

livenessProbe:
  path: /healthz
  port: 7000
  initialDelaySeconds: 10
  timeoutSeconds: 2
  periodSeconds: 10
image:
  name: listingsvc
  imageName: "mycluster.icp:8500/default/listing-mongo-microservice" 
  imagePullPolicy: Always
  ports:
    containerPort: 7000
  requests:
    cpu: "50m"
    memory: "200Mi"
  limits:
    cpu: "80m"
    memory: "210Mi"
  maxSurge: 1
  maxUnavailable: 0
  lifecycle:
    preStop:
      command: ["/bin/bash", "-c", "sleep 20"]


envOfSecrets:
  envMONGOUSERNAME:
    name: MONGOUSERNAME
    secretKeyRef:
      name: todomicroservice
      key: MONGOUSERNAME
  envMONGOPASSWORD:
    name: MONGOPASSWORD
    secretKeyRef:
      name: todomicroservice
      key: MONGOPASSWORD

envOfConfigmaps:
  envMONGOPORT:
    name: MONGOPORT
    configMapKeyRef:
      name: todomicroservice
      key: MONGOPORT
  envHOSTNAMEMONGODB:
    name: HOSTNAMEMONGODB
    configMapKeyRef:
      name: todomicroservice
      key: HOSTNAMEMONGODB


hpa:
  metadata:
    name: listingsvcmicroservicehpa
  spec:
    maxReplicas: 10
    minReplicas: 2
  metrics:
    pods:
      targetAverageValue: 20
    resource:
      name: cpu
      targetAverageUtilization: 50
    memory:
      targetAverageUtilization: 50
  scaleTargetRef:  
    name: listingsvc

service:
  serviceMetadata:
    name: listingsvc
    labels:
      app: listingsvc
  selector:
    selectorName: listingsvc
  servicePortConfiguration:
    protocol: TCP
    name: listingsvc
    type: ClusterIP
    port: 7000
    targetPort: 7000