apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: "{{ .Values.metadata.name }}"
  name: todomicroservice
  namespace: "{{ .Values.namespace }}"
data:
  MONGOPORT: "{{ .Values.mongodb.port }}"
  HOSTNAMEMONGODB: "{{ .Values.mongodb.host }}"